go_coffee_store_data_modeling:
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: go-coffee-project
      dataset: dev
      threads: 4
      keyfile: /home/ai_nerd/google_credential/go-coffee.json
    
    prod:
      type: bigquery
      method: service-account
      project: go-coffee-project
      dataset: analytics
      threads: 4
      keyfile: /home/ai_nerd/google_credential/go-coffee.json
  
  target: dev
